apiVersion: v1
kind: Service
metadata:
  labels:
    run: shiny-app
  name: shiny-app
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3838
  selector:
    run: shiny-app
  type: LoadBalancer
